### ISSUE TITLE
Bug: Ignoring default values for parameters with same name

### ISSUE THREAD

**Issue by Hiyorimi** [Kaixhin/FGLab#16]
If parameters in two projects share same name, adding the second project results in displaying first project default values for the parameters with the same name

**Comment by Kaixhin** [comment]
Can you reproduce this? I've removed all projects from a setup of FGLab, added `mnist.json`, adjusted the default parameters and renamed it to `mnist2.json`, and then added it as a second project. All default parameters are correct on both projects.

**Comment by Kaixhin** [comment]
@Hiyorimi any update on this?

**Comment by Hiyorimi** [comment]
I guess, I misconfigured parameters somehow. So the issue is closed
