### ISSUE TITLE
remote access

### ISSUE THREAD

**Issue by eyaler** [Kaixhin/FGLab#23]
how can i access the UI from a browser on a remote machine?

**Comment by barvinograd** [comment]
+1

**Comment by Kaixhin** [comment]
You need to be able to access the machine FGLab is running on from your remote machine via a local network/the internet. So you would replace `http://localhost:5080` with `http://lan-hostname:5080` or `http://public-address.com:5080`.

If this isn't obvious from the docs then please let me know where to adjust.
