### ISSUE TITLE
Ignoring User Input for Booleans

### ISSUE THREAD

**Issue by ColinKohler** [Kaixhin/FGLab#24]
When attempting to run a experiment with optional boolean flags FGLab ignores user input and instead sends True for all boolean arguments.

**Comment by Kaixhin** [comment]
Could you provide more information on your issue? FGLab is currently set up to take **mandatory** booleans, i.e., either the program receives `-option true` or `-option false`, which then needs to be parsed by the program appropriately. I'm working on another way to specify optional boolean flags, which is what I assume you are looking for?

**Comment by Kaixhin** [comment]
I've added the feature mentioned above in https://github.com/Kaixhin/FGMachine/commit/60ed6b07e0b5c968ce25f2d3b72aad837ad280ff. Have a look at the updated [FGMachine readme](https://github.com/Kaixhin/FGMachine#projects) for more details. Let me know if this works as you would expect.

**Comment by ColinKohler** [comment]
The new feature works as  expected, thanks!
